### ISSUE TITLE
Plugin appears totally broken after recent update to developer.android.com

### ISSUE THREAD

**Issue by brennantaylor** [romannurik/AndroidSDKSearchExtension#12]
I was planning on looking into it. Not just being a nag but I wanted to raise some noise.

**Comment by jgilfelt** [comment]
These Javascript reference URLs for GCM and Play Services now 404:
https://developer.android.com/reference/gcm_lists.js
https://developer.android.com/reference/gms_lists.js

Presumably they broke when the content moved over to https://developers.google.com/android/

Fortunately all the redirects for the class references contained within seem to work, so I copied the old .js files locally into the extension: https://github.com/jgilfelt/AndroidSDKSearchExtension/commit/184027e7e2a8355a7f73d3a2afc7afbdcb6c8819

You can get a working extension by disabling the production one and loading the unpacked extension from this branch: https://github.com/jgilfelt/AndroidSDKSearchExtension/tree/fix-omnibox-search

**Comment by romannurik** [comment]
Fixed in 0.3.6

**Comment by brennantaylor** [comment]
:+1:
