### ISSUE TITLE
Doesn't work with Vivaldi

### ISSUE THREAD

**Issue by Kisty** [romannurik/AndroidSDKSearchExtension#29]
Absolutely love this extension! Tried this with Vivaldi (1.8.770.56) browser which is based on Chromium but I think it hijacks tab behaviour (boo!) Any idea how to solve it?

Thanks so much @romannurik!

**Comment by romannurik** [comment]
Sorry (for the delay and for my almost certainly unsatisfying response), anything not Chrome isn't officially supported.

**Comment by Kisty** [comment]
No problem. Totally understand.
