### ISSUE TITLE
Missing init .js script, plugin broken!

### ISSUE THREAD

**Issue by SimonMarquis** [romannurik/AndroidSDKSearchExtension#31]
One of SDK reference JS files is no longer available, and endlessly retry:

https://github.com/romannurik/AndroidSDKSearchExtension/blob/e933077dbe929c6a3fef19e0ad9c9df90c7131b0/extension/background.js#L22

Is this script required to run the plugin?

Also, it would be great to have exponential backoff on the error callback:

https://github.com/romannurik/AndroidSDKSearchExtension/blob/e933077dbe929c6a3fef19e0ad9c9df90c7131b0/extension/background.js#L54-L57

For instance:

```javascript
var backoff = 5000;

function _error(script) {
  backoff *= 2;
  console.error('Failed to load ' + script + '. Retrying in ' + (backoff / 1000) + ' seconds.');
  window.setTimeout(init, backoff);
}
```

**Comment by SimonMarquis** [comment]
It seems that simply removing these two lines at least make the plugin work again:

https://github.com/romannurik/AndroidSDKSearchExtension/blob/e933077dbe929c6a3fef19e0ad9c9df90c7131b0/extension/background.js#L22 

https://github.com/romannurik/AndroidSDKSearchExtension/blob/e933077dbe929c6a3fef19e0ad9c9df90c7131b0/extension/background.js#L47

**Comment by romannurik** [comment]
Will close in 0.3.12
