### ISSUE TITLE
Can not view the source code of DexFile

### ISSUE THREAD

**Issue by verdigrass** [romannurik/AndroidSDKSearchExtension#33]
No display of `view source` button for:
https://developer.android.com/reference/dalvik/system/DexFile.html

And there is the same issue with classes in **dalvik/system** package:
https://developer.android.com/reference/dalvik/system/DexClassLoader.html

**Comment by romannurik** [comment]
The `dalvik` package and subpackages aren't listed [here](https://github.com/romannurik/AndroidSDKSearchExtension/blob/master/extension/ref-inject-code-search.js#L63); I'd welcome a pull request that fixes this!
