### ISSUE TITLE
VectorDrawableCompat link to source results in 404

### ISSUE THREAD

**Issue by alexjlockwood** [romannurik/AndroidSDKSearchExtension#42]
The documentation for VectorDrawableCompat is here: https://developer.android.com/reference/android/support/graphics/drawable/VectorDrawableCompat.html

Clicking on "view source" results in a 404: https://android.googlesource.com/platform/frameworks/support/+/refs/heads/master/graphics/drawable/animated/src/main/java/android/support/graphics/drawable/VectorDrawableCompat.java

Changing the word "animated" to "static" in the link fixes the issue: https://android.googlesource.com/platform/frameworks/support/+/refs/heads/master/graphics/drawable/static/src/main/java/android/support/graphics/drawable/VectorDrawableCompat.java

**Comment by romannurik** [comment]
Thanks for reporting! Want to submit a PR? I've been meaning to make the process a bit easier w/ tests and cleaner code structure but 🤷‍♂️

**Comment by alexjlockwood** [comment]
Would love to. But do you have any recommendations on how to test it? I've never worked with chrome extensions before.

**Comment by romannurik** [comment]
Development should be pretty straightforward:

1. Go to [chrome://extensions](chrome://extensions)
2. Turn on **Developer mode**
3. Press **Load unpacked extension** and navigate to the **extension** folder in this repo
4. Disable the official version of the extension so you only have the dev version active

When making changes to the code, you can reload the extension by clicking **Reload** on the extension.
