### ISSUE TITLE
Plugin does not seem to work with latest SDK page.

### ISSUE THREAD

**Issue by karczews** [romannurik/AndroidSDKSearchExtension#62]
I love the plugin and kept using for quite some time but it seems it does not work with latest SDK page. I'm not able to get view source link on any page. 

Also searching does not lead to any results - just opens up link with https://developer.android.com/?q=xx (but from what I see currently search should be done via https://developer.android.com/s/results/?q=xx).

**Comment by caseykulm** [comment]
I opened a PR to fix this #63

**Comment by romannurik** [comment]
Merged in #63, but don't have a timetable at the moment for publishing a new release... (feel free to clone the repo and use a local version for now!)

**Comment by mallamace** [comment]
Thank you for working towards updating this, this app is referenced in Grow with Google training course. There are roughly 1,000+ students who are potentially using this. Thank you for your continued support on this.

**Comment by romannurik** [comment]
Just published v0.3.15 which includes #63
