### ISSUE TITLE
Support androidx

### ISSUE THREAD

**Issue by bubenheimer** [romannurik/AndroidSDKSearchExtension#68]
1. Have the extension include androidx results in the omnibox search suggestions drop-down.
2. Show "view source" link on androidx documentation pages.

Item 1 is far more critical from my perspective than item 2. I pull up documentation all the time, but view the source only occasionally. So if item 1 is easy to add without adding the other, go ahead.

**Comment by romannurik** [comment]
@JakeWharton did you do anything for androidx in SdkSearch?
