### ISSUE TITLE
Marked as violating Chrome Web Store policy

### ISSUE THREAD

**Issue by arturdryomov** [romannurik/AndroidSDKSearchExtension#75]
Just tried to use the extension but it was disabled in Chrome and [has a warning on the extension panel](https://user-images.githubusercontent.com/200401/117446898-71b19600-af45-11eb-8810-a7b4c1d0e5df.png). The Chrome store page [responds with `404`](https://chrome.google.com/webstore/detail/hgcbffeicehlpmgmnhnkjbjoldkfhoin). The extension itself works fine if re-enabled but the warning is concerning.

**Comment by pocmo** [comment]
Afaik [SdkSearch](https://github.com/JakeWharton/SdkSearch) is the successor of this extension? :)

**Comment by JakeWharton** [comment]
Unfortunately SDK Search is also somewhat abandonware since Google relentlessly changes the data consumed by the app.

**Comment by romannurik** [comment]
@nickbutcher @chrisbanes any interest in taking over one of these extensions? Also hi ❤️❤️❤️

**Comment by chrisbanes** [comment]
No, for the same reason @JakeWharton mentioned 😂

**Comment by romannurik** [comment]
Lolz, K. It was a good run. @arturdryomov I should've posted this somewhere but I unpublished from the store since I don't have bandwidth to update anything to align with policy changes. I'll update the README at least.
