### ISSUE TITLE
RecyclerView "view source" goes to wrong URL

### ISSUE THREAD

**Issue by amlcurran** [romannurik/AndroidSDKSearchExtension#8]
Attempting to use the view source link on the recyclerview page goes to the wrong URL and results in a 404. Found on DefaultItemAnimator too (perhaps all RecyclerView source?)

Steps to reproduce:
- Navigate to https://developer.android.com/reference/android/support/v7/widget/RecyclerView.html
- Click the "view source" link

What should happen:
- Should navigate to https://android.googlesource.com/platform/frameworks/support/+/refs/heads/master/v7/recyclerview/src/android/support/v7/widget/RecyclerView.java

What does happen:
- Navigates to [https://android.googlesource.com/platform/frameworks/support/+/refs/heads/master/v7/**appcompat**/src/android/support/v7/widget/RecyclerView.java](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/master/v7/appcompat/src/android/support/v7/widget/RecyclerView.java) (note appcompat in the URL, not recyclerview
- Page 404s

**Comment by romannurik** [comment]
Should be easy enough to fix! Thanks for the report.
