### ISSUE TITLE
View Source broken on android.support.test classes

### ISSUE THREAD

**Issue by efung** [romannurik/AndroidSDKSearchExtension#9]
On a page like:

https://developer.android.com/reference/android/support/test/espresso/assertion/ViewAssertions.html

The (View Source) link goes to the platform/frameworks/base repository, leading to a 404. 

Instead, it should be looking in the platform/frameworks/testing repository. The source wasn't in the master branch, but I found it under the android-support-test branch.

**Comment by romannurik** [comment]
Looks like espresso was pulled from AOSP? It might help if we had a listing of android.support.test subpackages and where the source lived...

**Comment by Kisty** [comment]
It's broken for testing rules :(

E.g. http://developer.android.com/reference/android/support/test/rule/DisableOnAndroidDebug.html

**Comment by Kisty** [comment]
I'll go ahead and add all the support.test classes, not just Espresso :)

**Comment by Kisty** [comment]
Have made improvement to include most Android Testing Support Library sources, not just Espresso. #19.
